In [ ]:
import numpy as np
import pandas as pd
from datetime import datetime, timedelta
import random

np.random.seed(42)

random.seed(42)

num_transcations = 100

transcation_id = []

for i in range(1001, 1001 + num_transcations):
  txn_id = "TXN" + str(i).zfill(5)
  transcation_id.append(txn_id)
transcation_id[:5]

['TXN01001', 'TXN01002', 'TXN01003', 'TXN01004', 'TXN01005']

In [ ]:
start_date = datetime(2026,5,5)

transcation_amount = [199,299,349,499,599,699,799]

amounts = np.random.choice(transcation_amount, size=num_transcations)

print(f"Transcations amounts: {amounts}")

Transcations amounts: [799 499 599 799 349 599 599 799 299 349 799 349 349 599 499 349 699 599
 299 499 699 699 299 499 599 199 499 299 699 599 499 199 199 349 349 799
 299 499 499 799 699 699 799 699 349 499 799 499 199 349 599 349 799 599
 199 799 299 499 199 499 699 299 299 199 299 599 299 499 499 799 499 799
 499 599 799 349 699 199 499 299 499 299 699 699 699 299 499 699 599 799
 299 299 499 299 299 699 499 699 799 799]

In [ ]:
timestamps = []

for i in range(num_transcations):
  rand_day = np.random.randint(0,2)
  rand_hours = np.random.randint(9,22)
  rand_minutes = np.random.randint(0,59)

  timestamp = start_date + timedelta(days = rand_day, hours = rand_hours, minutes = rand_minutes)

  timestamps.append(timestamp)

print(timestamps, end = ' ')

[datetime.datetime(2026, 5, 6, 15, 56), datetime.datetime(2026, 5, 6, 16, 20), datetime.datetime(2026, 5, 6, 21, 17), datetime.datetime(2026, 5, 5, 13, 23), datetime.datetime(2026, 5, 6, 17, 44), datetime.datetime(2026, 5, 5, 21, 14), datetime.datetime(2026, 5, 5, 9, 24), datetime.datetime(2026, 5, 5, 17, 23), datetime.datetime(2026, 5, 5, 20, 7), datetime.datetime(2026, 5, 6, 19, 50), datetime.datetime(2026, 5, 5, 16, 34), datetime.datetime(2026, 5, 5, 9, 58), datetime.datetime(2026, 5, 5, 18, 38), datetime.datetime(2026, 5, 6, 17, 27), datetime.datetime(2026, 5, 5, 17, 7), datetime.datetime(2026, 5, 6, 10, 32), datetime.datetime(2026, 5, 6, 15, 22), datetime.datetime(2026, 5, 6, 16, 36), datetime.datetime(2026, 5, 5, 20, 39), datetime.datetime(2026, 5, 6, 19, 34), datetime.datetime(2026, 5, 5, 11, 36), datetime.datetime(2026, 5, 5, 11, 0), datetime.datetime(2026, 5, 5, 18, 54), datetime.datetime(2026, 5, 5, 15, 26), datetime.datetime(2026, 5, 5, 18, 41), datetime.datetime(2026, 5, 6, 21, 50), datetime.datetime(2026, 5, 5, 15, 48), datetime.datetime(2026, 5, 6, 21, 31), datetime.datetime(2026, 5, 6, 13, 22), datetime.datetime(2026, 5, 5, 21, 14), datetime.datetime(2026, 5, 5, 21, 35), datetime.datetime(2026, 5, 5, 15, 58), datetime.datetime(2026, 5, 5, 14, 27), datetime.datetime(2026, 5, 6, 18, 44), datetime.datetime(2026, 5, 6, 17, 52), datetime.datetime(2026, 5, 6, 20, 27), datetime.datetime(2026, 5, 6, 20, 19), datetime.datetime(2026, 5, 6, 19, 57), datetime.datetime(2026, 5, 5, 20, 24), datetime.datetime(2026, 5, 5, 9, 0), datetime.datetime(2026, 5, 5, 19, 56), datetime.datetime(2026, 5, 6, 21, 40), datetime.datetime(2026, 5, 5, 15, 5), datetime.datetime(2026, 5, 6, 19, 8), datetime.datetime(2026, 5, 6, 13, 32), datetime.datetime(2026, 5, 5, 18, 43), datetime.datetime(2026, 5, 6, 19, 53), datetime.datetime(2026, 5, 6, 16, 40), datetime.datetime(2026, 5, 6, 9, 48), datetime.datetime(2026, 5, 6, 12, 11), datetime.datetime(2026, 5, 6, 15, 1), datetime.datetime(2026, 5, 5, 9, 36), datetime.datetime(2026, 5, 5, 16, 16), datetime.datetime(2026, 5, 5, 9, 1), datetime.datetime(2026, 5, 6, 20, 53), datetime.datetime(2026, 5, 5, 13, 31), datetime.datetime(2026, 5, 5, 9, 18), datetime.datetime(2026, 5, 6, 10, 52), datetime.datetime(2026, 5, 6, 18, 31), datetime.datetime(2026, 5, 6, 15, 3), datetime.datetime(2026, 5, 5, 19, 55), datetime.datetime(2026, 5, 5, 9, 37), datetime.datetime(2026, 5, 6, 13, 51), datetime.datetime(2026, 5, 6, 14, 21), datetime.datetime(2026, 5, 5, 9, 8), datetime.datetime(2026, 5, 6, 19, 5), datetime.datetime(2026, 5, 6, 21, 2), datetime.datetime(2026, 5, 6, 20, 58), datetime.datetime(2026, 5, 6, 11, 25), datetime.datetime(2026, 5, 5, 11, 19), datetime.datetime(2026, 5, 6, 15, 51), datetime.datetime(2026, 5, 5, 9, 39), datetime.datetime(2026, 5, 6, 15, 17), datetime.datetime(2026, 5, 6, 9, 10), datetime.datetime(2026, 5, 6, 17, 24), datetime.datetime(2026, 5, 6, 15, 30), datetime.datetime(2026, 5, 6, 18, 34), datetime.datetime(2026, 5, 5, 20, 15), datetime.datetime(2026, 5, 6, 17, 51), datetime.datetime(2026, 5, 6, 9, 1), datetime.datetime(2026, 5, 5, 20, 4), datetime.datetime(2026, 5, 5, 19, 54), datetime.datetime(2026, 5, 5, 17, 34), datetime.datetime(2026, 5, 5, 11, 19), datetime.datetime(2026, 5, 6, 14, 55), datetime.datetime(2026, 5, 5, 16, 51), datetime.datetime(2026, 5, 5, 9, 7), datetime.datetime(2026, 5, 6, 14, 39), datetime.datetime(2026, 5, 6, 11, 47), datetime.datetime(2026, 5, 6, 17, 34), datetime.datetime(2026, 5, 5, 21, 17), datetime.datetime(2026, 5, 6, 10, 1), datetime.datetime(2026, 5, 6, 11, 15), datetime.datetime(2026, 5, 5, 17, 35), datetime.datetime(2026, 5, 5, 12, 32), datetime.datetime(2026, 5, 6, 13, 47), datetime.datetime(2026, 5, 6, 16, 7), datetime.datetime(2026, 5, 5, 11, 16), datetime.datetime(2026, 5, 6, 9, 47), datetime.datetime(2026, 5, 6, 19, 50)]

In [ ]:
method_options = ['UPI', 'CC', 'NetBaking', 'Wallet']
method_weights = [0.5, 0.3, 0.08, 0.12]

payments_methods = np.random.choice(method_options, size=num_transcations, p = method_weights)

payments_methods[:5]

array(['CC', 'UPI', 'CC', 'Wallet', 'UPI'], dtype='<U9')

In [ ]:
internal_ledger = pd.DataFrame({'transcation_id': transcation_id,
                                'amount':amounts, 'timestamp':timestamps,
                                'payment_methods':payments_methods,
                                'status': 'SUCCESS'})

In [ ]:
internal_ledger.head(5)

  transcation_id  amount           timestamp payment_methods   status
0       TXN01001     799 2026-05-06 15:56:00              CC  SUCCESS
1       TXN01002     499 2026-05-06 16:20:00             UPI  SUCCESS
2       TXN01003     599 2026-05-06 21:17:00              CC  SUCCESS
3       TXN01004     799 2026-05-05 13:23:00          Wallet  SUCCESS
4       TXN01005     349 2026-05-06 17:44:00             UPI  SUCCESS

In [ ]:
gateway_export = internal_ledger.copy()

print(f"Start gateway export with {len(gateway_export)} transcations.")

Start gateway export with 100 transcations.

In [ ]:
missing_indices = np.random.choice(gateway_export.index, size = 5, replace = False)

missing_txn_ids = []

for idx in missing_indices:
  txn_id = internal_ledger.loc[idx,'transcation_id']
  missing_txn_ids.append(txn_id)

print(f"Will remove these transcation ID's : {missing_txn_ids}")

Will remove these transcation ID's : ['TXN01098', 'TXN01006', 'TXN01056', 'TXN01038', 'TXN01071']

In [ ]:
gateway_export = gateway_export.drop(missing_indices)

In [ ]:
mismatch_indices = np.random.choice(gateway_export.index, size = 3, replace = False)


fee_options = [10,20,50,100]

for idx in mismatch_indices:
  original_amount = gateway_export.loc[idx,'amount']
  fee_deducted = random.choice(fee_options)
  new_amount = original_amount - fee_deducted
  gateway_export.loc[idx, 'amount'] = new_amount

  txn_id = gateway_export.loc[idx, 'transcation_id']
  print(f"{txn_id}: ₹{original_amount} -> ₹{new_amount} (fee: ₹{fee_deducted})")

TXN01084: ₹699 -> ₹689 (fee: ₹10)
TXN01077: ₹699 -> ₹689 (fee: ₹10)
TXN01066: ₹599 -> ₹549 (fee: ₹50)

In [ ]:
extra_transcation_1 = {
    'transcation_id':'TXN99901',
    'amount' : 199,
    'timestamp' : start_date + timedelta(hours=14),
    'payment_method' : 'UPI',
    'status' : 'SUCCESS'

}

extra_transaction_2 = {
    'transaction_id': 'TXN99902',
    'amount': 2999,
    'timestamp': start_date + timedelta(days=1, hours=10),
    'payment_method': 'Card',
    'status': 'SUCCESS'
}

extra_transactions = pd.DataFrame(['extra_transcation_1','extra_transaction_2'])

gateway_export = pd.concat([gateway_export, extra_transactions], ignore_index = True)

print(f"Added extra transactions: TXN99901, TXN99902")
print(f"Gateway now has {len(gateway_export)} transactions")

Added extra transactions: TXN99901, TXN99902
Gateway now has 97 transactions

In [ ]:
available_indices = gateway_export.index[:-2].tolist()
status_change_indices = np.random.choice(available_indices, size=2, replace=False)

for idx in status_change_indices:
    txn_id = gateway_export.loc[idx, 'transcation_id']
    gateway_export.loc[idx, 'status'] = 'FAILED'
    print(f"{txn_id}: Status changed to FAILED")

TXN01004: Status changed to FAILED
TXN01050: Status changed to FAILED

In [ ]:
print(f"\n{'='*50}")
print(f"Internal Ledger: {len(internal_ledger)} transactions")
print(f"Gateway Export: {len(gateway_export)} transactions")
print(f"{'='*50}")

==================================================
Internal Ledger: 100 transactions
Gateway Export: 97 transactions
==================================================

In [ ]:
print("=== Internal Ledger Summary ===")
print(f"Date Range : {internal_ledger['timestamp'].min()} to {internal_ledger['timestamp'].max()}")
print(f"Total amount : {internal_ledger['amount'].sum():,}")
print(internal_ledger['payment_methods'].value_counts())

=== Internal Ledger Summary ===
Date Range : 2026-05-05 09:00:00 to 2026-05-06 21:50:00
Total amount : 51,450
payment_methods
UPI          59
CC           21
Wallet       13
NetBaking     7
Name: count, dtype: int64

In [ ]:
print("\n === Gateway Export Summary === ")
print(f"Date range : {gateway_export['timestamp'].min()} to {gateway_export['timestamp'].max()}")
print(f"Total amount : {gateway_export['amount'].sum()}")
print(gateway_export['payment_methods'].value_counts())

 === Gateway Export Summary ===
Date range : 2026-05-05 09:00:00 to 2026-05-06 21:50:00
Total amount : 48285.0
payment_methods
UPI          57
CC           19
Wallet       12
NetBaking     7
Name: count, dtype: int64

In [ ]:
ledger_ids = set(internal_ledger['transcation_id'])
gateway_ids = set(gateway_export['transcation_id'])


print(f"Unique Ids in Ledger : {len(ledger_ids)}")
print(f"Unique Ids in Gateway : {len(gateway_ids)}")

Unique Ids in Ledger : 100
Unique Ids in Gateway : 96

In [ ]:
missing_in_gateway = ledger_ids - gateway_ids

print(f"\n Transcations in ledger but not in Gateway : {len(missing_in_gateway)}")
print(f"Transcation IDs : {missing_in_gateway}")

 Transcations in ledger but not in Gateway : 5
Transcation IDs : {'TXN01098', 'TXN01006', 'TXN01071', 'TXN01038', 'TXN01056'}

In [ ]:
missing_in_gateway_list = list(missing_in_gateway)

missing_in_gateway_df = internal_ledger[internal_ledger['transcation_id'].isin(missing_in_gateway_list)].copy()

missing_in_gateway_df['issue_type'] = 'MISSING_IN_GATEWAY'

total_missing_value = missing_in_gateway_df['amount'].sum()
print(f"\nTotal value at risk: ₹{total_missing_value:,}")

Total value at risk: ₹3,095

In [ ]:
missing_in_gateway_df

,transcation_id,amount,timestamp,payment_methods,status,issue_type
5,TXN01006,599,2026-05-05 21:14:00,Wallet,SUCCESS,MISSING_IN_GATEWAY
37,TXN01038,499,2026-05-06 19:57:00,CC,SUCCESS,MISSING_IN_GATEWAY
55,TXN01056,799,2026-05-05 13:31:00,UPI,SUCCESS,MISSING_IN_GATEWAY
70,TXN01071,499,2026-05-06 15:51:00,CC,SUCCESS,MISSING_IN_GATEWAY
97,TXN01098,699,2026-05-05 11:16:00,UPI,SUCCESS,MISSING_IN_GATEWAY

In [ ]:
common_ids = ledger_ids & gateway_ids

print(f"Transcations present in both : {len(common_ids)}")

Transcations present in both : 95

In [ ]:
common_ids_list = list(common_ids)

ledger_common = internal_ledger[internal_ledger['transcation_id'].isin(common_ids_list)].copy()
gateway_common = gateway_export[gateway_export['transcation_id'].isin(common_ids_list)].copy()

print(f"Transcation common in ledger : {len(ledger_common)}")
print(f"Transcation common in gateway : {len(gateway_common)}")

Transcation common in ledger : 95
Transcation common in gateway : 95

In [ ]:
comparsion = ledger_common.merge(gateway_common[['transcation_id', 'amount',
                                                'status']], on= 'transcation_id',
                                 suffixes=('_ledger', '_gateway'))

print(f"Merged comparison table: {len(comparsion)} rows")
comparsion.head()

Merged comparison table: 95 rows

,transcation_id,amount_ledger,timestamp,payment_methods,status_ledger,amount_gateway,status_gateway
0,TXN01001,799,2026-05-06 15:56:00,CC,SUCCESS,799.0,SUCCESS
1,TXN01002,499,2026-05-06 16:20:00,UPI,SUCCESS,499.0,SUCCESS
2,TXN01003,599,2026-05-06 21:17:00,CC,SUCCESS,599.0,SUCCESS
3,TXN01004,799,2026-05-05 13:23:00,Wallet,SUCCESS,799.0,FAILED
4,TXN01005,349,2026-05-06 17:44:00,UPI,SUCCESS,349.0,SUCCESS

In [ ]:
comparsion['amount_diff'] = comparsion['amount_ledger'] - comparsion['amount_gateway']

amount_mismatches = comparsion[comparsion['amount_diff'] != 0].copy()

print(f"Transcations with amount mismatch : {len(amount_mismatches)}")

if len(amount_mismatches ) > 0:
  total_discrepancy = amount_mismatches['amount_diff'].sum()
  print(f"Total discrepancy : , Rs {total_discrepancy}")

  print("\n Mismatch Details : ")
  print(amount_mismatches[['transcation_id', 'amount_ledger', 'amount_gateway',
                           'amount_diff']])

Transcations with amount mismatch : 3
Total discrepancy : , Rs 70.0

 Mismatch Details :
   transcation_id  amount_ledger  amount_gateway  amount_diff
62       TXN01066            599           549.0         50.0
72       TXN01077            699           689.0         10.0
79       TXN01084            699           689.0         10.0

In [ ]:
# Find status mismatches in our comparison table
status_mismatches = comparsion[comparsion['status_ledger'] != comparsion['status_gateway']].copy()

print(f"Transactions with status mismatch: {len(status_mismatches)}")

if len(status_mismatches) > 0:
    print("\n⚠️  CRITICAL — We think SUCCESS but gateway says otherwise:")
    print(status_mismatches[['transcation_id', 'amount_ledger', 'status_ledger', 'status_gateway']])

Transactions with status mismatch: 2

⚠️  CRITICAL — We think SUCCESS but gateway says otherwise:
   transcation_id  amount_ledger status_ledger status_gateway
3        TXN01004            799       SUCCESS         FAILED
47       TXN01050            349       SUCCESS         FAILED

In [ ]:
amount_mismatch_report = amount_mismatches[['transcation_id', 'amount_ledger',
                                            'amount_gateway','amount_diff']].copy()

amount_mismatch_report['issue_type'] = 'AMOUNT_MISMATCH'
amount_mismatch_report.columns = ['transcation_id', 'ledger_amount',
                                  'gateway_amount', 'difference', 'issue_type']
print(f"Amount mismatch records : {len(amount_mismatch_report)}")

amount_mismatch_report

Amount mismatch records : 3

   transcation_id  ledger_amount  gateway_amount  difference       issue_type
62       TXN01066            599           549.0        50.0  AMOUNT_MISMATCH
72       TXN01077            699           689.0        10.0  AMOUNT_MISMATCH
79       TXN01084            699           689.0        10.0  AMOUNT_MISMATCH